### PR TITLE
fix(vocabulary): [15] improve vocabulary

### LINKED ISSUE #15: Update API for search vocabularies

### PR DESCRIPTION
**Pull request by duynk1801**
##### Make sure all of them are checked before assigning reviewers

- [ X] There's no conflict with the main branch
- [x ] All checks has been successfully passed
- [ x] There is no warnings in the console
- [x ] I have checked the task satisfies what is asked in project
- [x ] I did the QA part and I think there are no bugs
- [x ] The title's format is correct 

___

### **PR Type**
enhancement, bug_fix

___

### **Description**
- Enhanced API type definitions and error handling by adding new interfaces and updating existing ones.
- Updated vocabulary fetching logic to use a new API method with a strict search option.
- Refactored vocabulary search component to use a new service method and integrated a new `SearchResult` component.
- Implemented a new vocabulary service with pagination and filtering options.
- Added new dictionary entries for "History search" in both English and Vietnamese.
- Removed old vocabulary service implementation and updated endpoint definitions.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>api.type.ts</strong><dd><code>Enhance API type definitions and error handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/@types/api.type.ts

<li>Added new interfaces for handling API responses and errors.<br> <li> Updated existing interfaces to include additional fields.<br> <li> Modified API request types to use new interfaces.<br>

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-7d4f06fcf45494471367b1523f1e497f5814ed2d176af9b13dde799ff18d2f1f">+96/-14</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>page.tsx</strong><dd><code>Update vocabulary fetching logic with strict search</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/app/[lang]/(home)/vocabulary/[word]/page.tsx

<li>Updated vocabulary fetching logic to use new API method.<br> <li> Added strict search option for vocabulary retrieval.<br>

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-b9893fa758b3e438af4c90b986103fb817ca35a472f19c1d4b0c77338603c9a2">+6/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Refactor vocabulary search and integrate SearchResult component</code></dd></summary>
<hr>

src/components/features/vocabulary-input/index.tsx

<li>Refactored vocabulary search to use new service method.<br> <li> Integrated <code>SearchResult</code> component for displaying results.<br>

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-6f1ce0546f3a74c99d49eed809c96ba3732ee590a3eb493aa3feb9eeafd08870">+40/-27</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>search-result.tsx</strong><dd><code>Implement SearchResult component for vocabulary search</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/features/vocabulary-input/search-result.tsx

<li>Created new <code>SearchResult</code> component for displaying search results.<br> <li> Implemented logic for handling search result interactions.<br>

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-fe1f28656e0a5b26c62e607c434e4104b50ce2faa7bb6f803fed4d2d96d262cc">+65/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>dev-log.ts</strong><dd><code>Enhance devLog function for multiple arguments</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/lib/dev-log.ts

- Updated `devLog` function to accept multiple arguments.

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-47aca42d44d3f22169d3057d44a80d54d19ab4af36c6489b5c6ee8b3249de38d">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>vocabulaties.ts</strong><dd><code>Implement new vocabulary service with pagination</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/services/vocabulaties.ts

<li>Implemented new vocabulary service with enhanced request handling.<br> <li> Added pagination and filtering options for vocabulary retrieval.<br>

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-0eafa90adf9a6ec3b271763904203cf0ddc23b9bd57236ffa7d94b7f6ac223d2">+31/-8</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>en.json</strong><dd><code>Update English dictionary with new entry</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/dictionaries/en.json

- Added new dictionary entry for "History search".

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-cf8c01eff8cb7173dfa28cfd3bf467a058671d1e29bd9657dc6947ee7247b096">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>vi.json</strong><dd><code>Update Vietnamese dictionary with new entry</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/dictionaries/vi.json

- Added new dictionary entry for "History search".

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-cadf938b33a18ff53dc9d0f59a7cf376fc0facee5a58b9f5fe43067cadbfbe43">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Formatting</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Adjust header component formatting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/layouts/header/index.tsx

- Minor formatting adjustments in the header component.

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-3f8c1afe7a42a9de4b8bba6a408033b842ff236aa8b3c9b34495507440d2db98">+4/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Cleanup</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>vocabularies.ts</strong><dd><code>Remove old vocabulary service implementation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/services/csr/vocabularies.ts

- Removed old vocabulary service implementation.

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-f1a7bf7195c828d0894da6abbc74453144b5036242ae13a532962d3cad3ae114">+0/-45</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>end-points.ts</strong><dd><code>Update vocabulary endpoint definitions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/services/end-points.ts

- Updated vocabulary endpoint definitions.

</details>

  </td>
  <td><a href="https://github.com/tranduybau/e-speak-fe/pull/16/files#diff-b33e82c5c8e0d5d6d17a6ca7aae33d18dcacb65abf284d445f7563e8df0a661c">+2/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

File: src/components/features/vocabulary-input/index.tsx [hunk 1]
```diff
@@ -6,9 +6,11 @@ import { Loader2, Search } from 'lucide-react'
 
 import { Input } from '@/components/ui/input'
 
-import VocabulariesServices from '@/services/csr/vocabularies'
+import VocabulariesService from '@/services/vocabulaties'
```
Comment (tranduybau) [inline src/components/features/vocabulary-input/index.tsx:9]: Screenshot 2024-11-24 at 21 50 25
Wrong text. Please update it

File: src/app/[lang]/(home)/vocabulary/[word]/page.tsx [hunk 2]
```diff
@@ -17,12 +17,15 @@ export default async function Vocabulary(props: VocabularyPageProps) {
...
   const dictionary = await getDictionary(params.lang)
 
-  const data = await VocabulariesService.getWordDetails(params.word)
+  const data = await VocabulariesService.getVocabs({
+    text: params.word,
+    is_strict: true,
+  })
 
-  if (data.isError) {
+  if (data.isError || data?.data?.length === 0) {
```
Comment (tranduybau) [inline src/app/[lang]/(home)/vocabulary/[word]/page.tsx:25]: Screenshot 2024-11-24 at 21 51 58

Please make sure the data is available, Don't abuse the structure?.

File: src/components/features/vocabulary-input/index.tsx [hunk 3]
```diff
@@ -68,30 +76,35 @@ export default function VocabularySearch({ dictionary }: VocabularySearchProps)
...
+        searchTerm={searchTerm}
+        isDisplay={isFocus}
+        loading={loading}
+        onClose={() => {
+          setIsFocus(false)
+          // setSearchTerm('')
+        }}
+      />
+
+      {/* {!records?.isError && !!records?.data?.length && searchTerm && ( */}
```
Comment (tranduybau) [inline src/components/features/vocabulary-input/index.tsx:90]: Screenshot 2024-11-24 at 21 54 33

Remove un-used
